// <auto-generated />
namespace LMS_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addExamPeriod : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addExamPeriod));
        
        string IMigrationMetadata.Id
        {
            get { return "202409170822411_addExamPeriod"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
